community_name: "SaveTogether"
community_tagline: "Philanthropy for Everyday People"
community_description:  "Help someone reach their dream to get an education, start a business, or buy a home. Donate $1 today to match their savings goal."
support_email:  "info@savetogether.org"
meta_description: 'Help someone reach their dream to get an education, start a business, or buy a home. Donate $1 today to match their savings goal.'
meta_keywords: 'Savings, working families, low-income, poverty, microfinance, microsavings, education, microbusiness, home, match, donations, goals, social, community'
#sections_enabled: ['photos', 'posts', 'clippings', 'contests', 'categories', 'events']
#sections_enabled: ['photos']
exception_notification_email: "tom@savetogether.org"
paypal_account: "paypal@savetogether.org"
app_url: "http://localhost:3000"
paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
paypal_return_protocol: "http"
enable_optify: true

photo:
  missing_thumb: '/plugin_assets/community_engine/images/icon_missing_thumb.gif'
  missing_medium: "/plugin_assets/community_engine/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "c100x100!", mini: "c155x155!", small: "c210x210!", medium: "c290x320!", large: "664>"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    #storage: 'file_system'
    storage: 's3'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
    path_prefix: 'public/system/photos'
    processor: 'rmagick'
